name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B tests/build -S tests

      - name: Build
        run: cmake --build tests/build

      - name: Run
        run: ctest --test-dir tests/build -V
